package com.mycompany.views;

import com.mycompany.heycha.DAOClientsImpl;
import com.mycompany.interfaces.DAOClients;
import com.mycompany.interfaces.Styleable;
import com.mycompany.models.ModelClients;
import java.awt.Color;

public class UpClients extends javax.swing.JPanel implements Styleable {

    boolean isEditable;
    ModelClients clientEditable;

    public UpClients(boolean isDarkModeEnabled) {
        initComponents();
        updateStyles(isDarkModeEnabled);
        initStyles();
    }

    public UpClients(ModelClients client, boolean isDarkModeEnabled) {
        initComponents();
        isEditable = true;
        clientEditable = client;
        updateStyles(isDarkModeEnabled);
        initStyles();
    }

    @Override
    public void updateStyles(boolean isDarkModeEnabled) {
        if (isDarkModeEnabled) {
            title.setForeground(Color.white);
            bg.putClientProperty("FlatLaf.style", "background: #172030");
            DataUpdateBtn.putClientProperty("FlatLaf.style", "background: #0c9294");
        } else {
            title.setForeground(Color.black);
            bg.putClientProperty("FlatLaf.style", "background: #FFFFFF");
            DataUpdateBtn.putClientProperty("FlatLaf.style", "background: #125AAD");
        }
    }

    private void initStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        nameLbl.putClientProperty("FlatLaf.styleClass", "h2");
        cellphoneLbl.putClientProperty("FlatLaf.styleClass", "h2");
        cityLbl.putClientProperty("FlatLaf.styleClass", "h2");
        directionLbl.putClientProperty("FlatLaf.styleClass", "h2");

        nameTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del cliente.");
        cellphoneTxt.putClientProperty("JTextField.placeholderText", "Ingrese el telefono del cliente.");
        cityTxt.putClientProperty("JTextField.placeholderText", "Ingrese la ciudad donde vive el cliente.");
        directionTxt.putClientProperty("JTextField.placeholderText", "Ingrese la dirección donde vive el cliente.");

        if (isEditable) {
            title.setText("Editar producto.");
            DataUpdateBtn.setText("Guardar");

            if (clientEditable != null) {
                nameTxt.setText(clientEditable.getName());
                cellphoneTxt.setText(clientEditable.getCellphone().toString());
                cityTxt.setText(clientEditable.getCity());
                directionTxt.setText(clientEditable.getDirection());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        cellphoneLbl = new javax.swing.JLabel();
        cityLbl = new javax.swing.JLabel();
        directionLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        directionTxt = new javax.swing.JTextArea();
        cityTxt = new javax.swing.JTextField();
        cellphoneTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        DataUpdateBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(764, 436));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Subir Nuevo Cliente.");

        nameLbl.setText("Nombre:");

        cellphoneLbl.setText("Teléfono:");

        cityLbl.setText("CIudad:");

        directionLbl.setText("DIrección:");

        directionTxt.setColumns(20);
        directionTxt.setRows(5);
        jScrollPane1.setViewportView(directionTxt);

        DataUpdateBtn.setBackground(new java.awt.Color(18, 90, 173));
        DataUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DataUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        DataUpdateBtn.setText("Subir");
        DataUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(637, 637, 637))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(cellphoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(380, 380, 380))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(cityLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(390, 390, 390))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(directionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(377, 377, 377))
                    .addComponent(nameTxt)
                    .addComponent(jScrollPane1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(384, 384, 384))
                    .addComponent(cellphoneTxt)
                    .addComponent(cityTxt))
                .addGap(18, 18, 18)
                .addComponent(DataUpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(nameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cellphoneLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cityLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(directionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DataUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataUpdateBtnActionPerformed
        String name = nameTxt.getText();
        Integer cellphone = Integer.valueOf(cellphoneTxt.getText());
        String city = cityTxt.getText();
        String direction = directionTxt.getText();

        ModelClients client = isEditable ? clientEditable : new ModelClients();
        client.setName(name);
        client.setCellphone(cellphone);
        client.setCity(city);
        client.setDirection(direction);

        try {
            DAOClients dao = new DAOClientsImpl();

            if (!isEditable) {
                dao.record(client);
            } else {
                //implementar modificacion del cliente
            }
            String succecssMsg = isEditable ? "modificado" : "registrado";
            javax.swing.JOptionPane.showMessageDialog(this, "Datos " + succecssMsg + " correctamente. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (!isEditable) {
                emptyFields();
            }
        } catch (Exception e) {
            String errorMsg = isEditable ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " los datos. \n" + e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_DataUpdateBtnActionPerformed
    private void emptyFields() {
        nameTxt.setText("");
        cellphoneTxt.setText("");
        cityTxt.setText("");
        directionTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DataUpdateBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cellphoneLbl;
    private javax.swing.JTextField cellphoneTxt;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel directionLbl;
    private javax.swing.JTextArea directionTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
