package com.mycompany.views;

import com.mycompany.heycha.DAOClientsImpl;
import com.mycompany.heycha.DAOProductsImpl;
import com.mycompany.heycha.DAOProductsSizesImpl;
import com.mycompany.heycha.DAOSalesImpl;
import com.mycompany.interfaces.DAOClients;
import com.mycompany.interfaces.DAOProductSizes;
import com.mycompany.interfaces.DAOProducts;
import com.mycompany.interfaces.DAOSales;
import com.mycompany.interfaces.Styleable;
import com.mycompany.models.ModelClients;
import com.mycompany.models.ModelSales;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

public class UpSales extends javax.swing.JPanel implements Styleable {

    DAOProducts daoProduct = new DAOProductsImpl();
    DAOClients daoClients = new DAOClientsImpl();
    private DefaultTableModel modelProduct;
    private DefaultTableModel modelClient;

    public UpSales(boolean isDarkModeEnabled) {
        initComponents();
        updateStyles(isDarkModeEnabled);
        initStyles();
        createProductTable();
    }

    @Override
    public void updateStyles(boolean isDarkModeEnabled) {
        if (isDarkModeEnabled) {
            title.setForeground(Color.white);
            bg.putClientProperty("FlatLaf.style", "background: #172030");
            btnDataUpdate.putClientProperty("FlatLaf.style", "background: #0c9294");
        } else {
            title.setForeground(Color.black);
            bg.putClientProperty("FlatLaf.style", "background: #FFFFFF");
            btnDataUpdate.putClientProperty("FlatLaf.style", "background: #125AAD");
        }
    }

    private void initStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        productNameLbl.putClientProperty("FlatLaf.styleClass", "h2");
        quantitySalesLbl.putClientProperty("FlatLaf.styleClass", "h2");
        clientNameLbl.putClientProperty("FlatLaf.styleClass", "h2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        btnDataUpdate = new javax.swing.JButton();
        clientNameLbl = new javax.swing.JLabel();
        quantitySalesLbl = new javax.swing.JLabel();
        productNameLbl = new javax.swing.JLabel();
        spinnerQuantity = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        productNameTxt = new javax.swing.JTextField();
        clientNameTxt = new javax.swing.JTextField();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Subir Nueva Venta.");

        btnDataUpdate.setBackground(new java.awt.Color(18, 90, 173));
        btnDataUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDataUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnDataUpdate.setText("Subir");
        btnDataUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataUpdateActionPerformed(evt);
            }
        });

        clientNameLbl.setText("Nombre del cliente (Opcional):");

        quantitySalesLbl.setText("Cantidad:");

        productNameLbl.setText("Nombre del producto:");

        spinnerQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        productNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productNameTxtKeyReleased(evt);
            }
        });

        clientNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientNameTxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(646, 646, 646))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(clientNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(72, 72, 72))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(quantitySalesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(186, 186, 186))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productNameTxt)
                                    .addComponent(clientNameTxt))
                                .addGap(30, 30, 30)))
                        .addComponent(jScrollPane1)
                        .addGap(16, 16, 16))))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnDataUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(205, 205, 205))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(title)
                .addGap(36, 36, 36)
                .addComponent(productNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(productNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantitySalesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clientNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(btnDataUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataUpdateActionPerformed
//        Integer productId = cmbProductsName.getSelectedIndex() == -1 ? null : cmbProductsName.getSelectedIndex() + 1;
//        Integer clientId = cmbClientsName.getSelectedIndex() == -1 ? null : cmbClientsName.getSelectedIndex() + 1;
//        int quantity = (int) spinnerQuantity.getValue();
//        boolean incorrectData = productId == null || clientId == null || quantity < 1;
//        if (incorrectData) {
//            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese los datos correctamente\n", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
//            cmbProductsName.requestFocus();
//            return;
//        }
        ModelSales sale = new ModelSales();
//        sale.setProductId(productId);
//        sale.setClientId(clientId);
//        sale.setQuantitySold(quantity);
        LocalDate date = LocalDate.now();
        sale.setDate(date);
        System.out.println(sale.getDate());

        try {
            DAOSales dao = new DAOSalesImpl();
            dao.record(sale);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error. \n" + e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDataUpdateActionPerformed

    private void productNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameTxtKeyReleased
        createProductTable();
    }//GEN-LAST:event_productNameTxtKeyReleased
    private void createProductTable() {
        clientNameTxt.setText("");
        modelProduct = new DefaultTableModel();
        jTable1.setDefaultEditor(Object.class, null);
        modelProduct.addColumn("ID");
        modelProduct.addColumn("Nombre");
        modelProduct.addColumn("Precio");
        modelProduct.addColumn("Descripcion");
        modelProduct.addColumn("Descuento");
        modelProduct.addColumn("Marca");
        modelProduct.addColumn("Categoria");
        modelProduct.setRowCount(0);
        String nameToFind = productNameTxt.getText();
        String brandSelected = "NINGUNO";
        String categorySelected = "NINGUNO";
        try {
            daoProduct.consult(nameToFind, brandSelected, categorySelected).forEach((p) -> modelProduct.addRow(new Object[]{p.getId(), p.getName(), p.getPrice(), p.getDescription(), p.getDiscount(), p.getBrand(), p.getCategory()}));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error. \n" + e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        jTable1.setModel(modelProduct);
    }

    private void clientNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientNameTxtKeyReleased
        createClientTable();
    }//GEN-LAST:event_clientNameTxtKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0 && evt.getClickCount() == 2) {
            int id = (int) jTable1.getValueAt(row, 0);
            if (jTable1.getModel() == modelProduct) {
                System.out.println("ID del producto: " + id);
                ViewProducts p = new ViewProducts();
                p.loadProductSizes(jTable1);
                
            } else if (jTable1.getModel() == modelClient) {
                System.out.println("ID del cliente: " + id);
                
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked
    private void setSaleFields(int id) {

    }

    private void createClientTable() {
        productNameTxt.setText("");
        modelClient = new DefaultTableModel();
        jTable1.setDefaultEditor(Object.class, null);
        modelClient.addColumn("ID");
        modelClient.addColumn("Nombre");
        modelClient.addColumn("Telefono");
        modelClient.addColumn("Ciudad");
        modelClient.addColumn("Dirección");
        modelClient.setRowCount(0);
        String nameToFind = clientNameTxt.getText();

        try {
            daoClients.consult(nameToFind).forEach((c) -> modelClient.addRow(new Object[]{c.getId(), c.getName(), c.getCellphone(), c.getCity(), c.getDirection()}));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error. \n" + e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        jTable1.setModel(modelClient);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnDataUpdate;
    private javax.swing.JLabel clientNameLbl;
    private javax.swing.JTextField clientNameTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel productNameLbl;
    private javax.swing.JTextField productNameTxt;
    private javax.swing.JLabel quantitySalesLbl;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
